import puppeteer from 'puppeteer-core';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, '..', 'shots');
const CHROME = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const BASE = 'http://localhost:5173';
const wait = (ms) => new Promise((r) => setTimeout(r, ms));

const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
page.on('pageerror', (e) => console.log('PAGE-EXCEPTION:', e.message));
await page.setViewport({ width: 1366, height: 900 });
await page.goto(`${BASE}/login`, { waitUntil: 'networkidle2' });
await page.evaluate(() => [...document.querySelectorAll('button')].find((b) => /sign in/i.test(b.textContent))?.click());
await page.waitForFunction(() => document.body.innerText.toLowerCase().includes('cash position'), { timeout: 20000 });
await page.goto(`${BASE}/analytics`, { waitUntil: 'networkidle2' });
await page.waitForFunction(() => document.body.innerText.toLowerCase().includes('break-even'), { timeout: 15000 });
await wait(1500);
await page.evaluate(() => [...document.querySelectorAll('h3')].find((h) => /expense breakout/i.test(h.textContent))?.scrollIntoView({ block: 'start' }));
await wait(800);
await page.screenshot({ path: join(outDir, '14-analytics-bottom.png') });
console.log('shot 14-analytics-bottom');
await browser.close();
